# Generated by Django 6.0.1 on 2026-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestock",
            name="animal_type",
            field=models.CharField(
                choices=[("cow", "Cow"), ("goat", "Goat"), ("poultry", "Poultry")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="breed",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="daily_waste_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(
                choices=[("Healthy", "Healthy"), ("Sick", "Sick")],
                default="Healthy",
                max_length=20,
            ),
        ),
    ]
