# Generated by Django 6.0.1 on 2026-02-06 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_alter_livestock_animal_type_alter_livestock_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestock",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("Healthy", "Healthy"),
                    ("Sick", "Sick"),
                    ("Under Obervation", "Under Obervation"),
                ],
                default="Healthy",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LivestockHealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccination", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("weight_kg", models.FloatField()),
                (
                    "recorded_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "livestock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.livestock",
                    ),
                ),
            ],
        ),
    ]
