# Generated by Django 6.0.1 on 2026-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_alter_livestock_health_status_livestockhealthlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestockhealthlog",
            name="recorded_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="livestockhealthlog",
            name="vaccination",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="livestockhealthlog",
            name="weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
