# Generated by Django 6.0.1 on 2026-02-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_alter_livestockhealthlog_recorded_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivestockYieldLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("milk_litre", models.FloatField(blank=True, null=True)),
                ("eggs_count", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "livestock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_logs",
                        to="farmer.livestock",
                    ),
                ),
            ],
        ),
    ]
