# Generated by Django 6.0.1 on 2026-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0005_livestockyieldlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganicFertilizerCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("nitrogen_required_kg", models.FloatField()),
                ("manure_type", models.CharField(max_length=50)),
                ("manure_required_kg", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
