# Generated by Django 6.0.1 on 2026-02-07 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0006_organicfertilizercalculation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organicfertilizercalculation",
            name="manure_required_kg",
            field=models.FloatField(help_text="Equivalent manure in kg"),
        ),
        migrations.AlterField(
            model_name="organicfertilizercalculation",
            name="nitrogen_required_kg",
            field=models.FloatField(help_text="Nitrogen needed in kg"),
        ),
        migrations.CreateModel(
            name="CompostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manure_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("duration_days", models.IntegerField(default=30)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
