# Generated by Django 6.0.1 on 2026-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "farmer",
            "0007_alter_organicfertilizercalculation_manure_required_kg_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganicMarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_name", models.CharField(max_length=100)),
                ("product_type", models.CharField(max_length=100)),
                ("quantity_kg", models.FloatField()),
                ("price_per_kg", models.FloatField()),
                ("location", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
