# Generated by Django 6.0.1 on 2026-02-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0008_organicmarketplacelisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestockhealthlog",
            name="health_status",
            field=models.CharField(default="Healthy", max_length=50),
        ),
    ]
