# Generated by Django 6.0.1 on 2026-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0009_livestockhealthlog_health_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
