# Generated by Django 6.0.1 on 2026-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0010_crop"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nitrogen", models.FloatField()),
                ("phosphorus", models.FloatField()),
                ("potassium", models.FloatField()),
                ("ph", models.FloatField()),
                ("tested_on", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
