# Generated by Django 6.0.1 on 2026-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0011_soiltest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Crop",
        ),
        migrations.AddField(
            model_name="organicmarketplacelisting",
            name="nitrogen",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="organicmarketplacelisting",
            name="phosphorus",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="organicmarketplacelisting",
            name="potassium",
            field=models.FloatField(default=0),
        ),
    ]
