# Generated by Django 6.0.1 on 2026-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0012_delete_crop_organicmarketplacelisting_nitrogen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("crop", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("subsidy_amount", models.CharField(max_length=100)),
                ("eligibility", models.TextField()),
                ("apply_link", models.URLField()),
            ],
        ),
    ]
