# Generated by Django 6.0.1 on 2026-03-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0013_subsidyscheme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubsidyScheme",
        ),
    ]
