# Generated by Django 6.0.1 on 2026-03-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0015_yieldhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yieldhistory",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="yieldhistory",
            name="ph",
        ),
        migrations.RemoveField(
            model_name="yieldhistory",
            name="phosphorus",
        ),
        migrations.RemoveField(
            model_name="yieldhistory",
            name="potassium",
        ),
        migrations.RemoveField(
            model_name="yieldhistory",
            name="risk_level",
        ),
    ]
