# Generated by Django 6.0.1 on 2026-03-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0016_remove_yieldhistory_crop_remove_yieldhistory_ph_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YieldHistory",
        ),
    ]
