# Generated by Django 6.0.1 on 2026-03-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0018_yieldhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YieldHistory",
        ),
    ]
