# Generated by Django 6.0.1 on 2026-02-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("Cow Manure", "Cow Manure"),
                            ("Goat Manure", "Goat Manure"),
                            ("Poultry Waste", "Poultry Waste"),
                            ("Vermicompost", "Vermicompost"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity_kg", models.FloatField()),
                ("start_date", models.DateField()),
                ("ready_date", models.DateField()),
                ("is_ready", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_id", models.CharField(max_length=50, unique=True)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("Cow", "Cow"),
                            ("Goat", "Goat"),
                            ("Buffalo", "Buffalo"),
                            ("Poultry", "Poultry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=50)),
                ("age_years", models.FloatField()),
                ("weight_kg", models.FloatField()),
                ("last_vaccination", models.DateField(blank=True, null=True)),
                ("health_status", models.CharField(default="Healthy", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
