# Generated by Django 6.0.1 on 2026-02-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organic", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Livestock",
        ),
    ]
