# Generated by Django 6.0.1 on 2026-03-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organic", "0002_delete_livestock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompostLog",
        ),
    ]
